'use strict';
(()=>{
const A=Arcana,K=Knowledge,S=Spellcraft,manaPulse={},$=s=>document.querySelector(s),overlay=$('#overlay'),hud=$('#hud'),canvas=$('#world');
const STORE='palimpsest.save.v1',BACKUP=STORE+'.backup',OPTIONS='palimpsest.options.v1';
let settings={volume:.42,music:.22,shake:true,particles:true};try{Object.assign(settings,JSON.parse(localStorage.getItem(OPTIONS)||'{}'));}catch{}
let sim=new Simulation(A.createState()),renderer=new WorldRenderer(canvas),mode='title',keys=new Set(),mouse={x:innerWidth*.6,y:innerHeight*.5,down:false},last=performance.now(),uiTimer=0,mapTimer=0,saveFailed=false,sessionStarted=false,editor=null,returnTo='pause';
class Sound{
constructor(){this.ctx=null;this.timer=0;this.notes=0;this.volume=settings.volume;this.music=settings.music;}
start(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=.65;this.master.connect(this.ctx.destination);}if(this.ctx.state==='suspended')this.ctx.resume();}
tone(freq,duration,volume=.15,type='sine',delay=0,slide=0){if(!this.ctx||this.ctx.state!=='running')return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,slide),t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.05);}
fx(name,element){const v=this.volume;if(name==='cast'){const f=[196,294,220,440,330,523,174,392][A.MANA.findIndex(m=>m.id===element)]||260;this.tone(f,.25,v*.17,'triangle',0,f*1.8);this.tone(f*2,.18,v*.05,'sine',.03);}if(name==='hurt')this.tone(90,.2,v*.2,'sawtooth',0,42);if(name==='kill'){this.tone(165,.16,v*.13,'triangle',0,70);this.tone(440,.3,v*.06);}if(name==='pickup')this.tone(880,.16,v*.045);if(name==='dry')this.tone(110,.1,v*.09,'triangle');if(name==='dash')this.tone(170,.25,v*.09,'triangle',0,640);if(name==='shrine'||name==='boss'){[196,246.94,293.66,392].forEach((n,i)=>this.tone(n,1.8,v*.15,'sine',i*.13));}}
update(dt){if(!this.ctx||this.music<=0)return;this.timer-=dt;if(this.timer<=0){this.timer=3.6;const chords=[[146.83,220,293.66],[130.81,196,261.63],[164.81,220,329.63],[130.81,196,293.66]],chord=chords[Math.floor(this.notes/2)%4];chord.forEach((n,i)=>this.tone(n,5,this.music*.075,'sine',i*.13));this.tone(chord[this.notes%3]*2,2.8,this.music*.065,'sine',.7);this.notes++;}}
}
const audio=new Sound();
const CONTROL_STORE='palimpsest.controls.v1';
let storedControls;try{storedControls=JSON.parse(localStorage.getItem(CONTROL_STORE));}catch{}
const controls=new ArcaneControls.Controller(storedControls);let capturing=null;
function saveControls(){try{localStorage.setItem(CONTROL_STORE,JSON.stringify(controls.preferences));}catch{toast('Не удалось сохранить управление. Изменения действуют до закрытия игры.');}}
function toggleCasting(){mouse.down=false;controls.toggle();saveControls();updateHUD();toast(controls.preferences.mode==='live'?'Составление на ходу: наберите аспекты, выберите форму, нажмите ЛКМ.':'Готовые ячейки: выберите заклинание и нажмите ЛКМ.');}
function chooseCasting(i){mouse.down=false;if(controls.preferences.mode==='live'){if(!controls.choose(i,sim.s.research))toast('Печать требует исследования I в обсерватории.');}else sim.s.selected=i;updateHUD();}
function castCurrent(){return controls.cast(sim,renderer.screenToWorld(mouse.x,mouse.y));}
function controlName(action){return ArcaneControls.LABELS[action]||mana(action).name;}
function controlsScreen(back){setMode('controls');returnTo=back;capturing=null;
shell('Клавиши и магия',`<p class="tiny">Нажмите назначение, затем новую клавишу. Занятые клавиши меняются местами. Esc отменяет выбор. Стрелки движения и F11 остаются постоянными.</p><div class="row control-mode"><button id="mode-slots" class="${controls.preferences.mode==='slots'?'primary':''}">Готовые ячейки</button><button id="mode-live" class="${controls.preferences.mode==='live'?'primary':''}">Составление на ходу</button><button id="reset-keys">Сбросить клавиши</button></div><p id="capture-hint" class="tiny">Раскладка не влияет на физическое расположение клавиш.</p><div class="bindings-grid">${Object.keys(ArcaneControls.DEFAULTS).map(a=>`<button data-binding="${a}" class="binding"><span>${controlName(a)}</span><b>${controls.key(a)}</b></button>`).join('')}</div><p class="tiny">ЛКМ применяет рецепт и повторяет при удержании. ПКМ — искра. В режиме составления колесо выбирает форму; рецепт остаётся после применения. Модификатор перебирается отдельной клавишей. Неизвестные аспекты можно испытывать, но их свойства здесь не раскрываются.</p>`,true);
$('.panel').classList.add('controls-panel');
for(const value of ['slots','live'])bind('mode-'+value,()=>{controls.preferences.mode=value;saveControls();controlsScreen(back);});
bind('reset-keys',()=>{controls.preferences.bindings={...ArcaneControls.DEFAULTS};saveControls();controlsScreen(back);});
document.querySelectorAll('[data-binding]').forEach(el=>el.onclick=()=>{capturing=el.dataset.binding;document.querySelectorAll('[data-binding]').forEach(b=>b.classList.remove('active'));el.classList.add('active');$('#capture-hint').textContent='Новая клавиша: '+controlName(capturing)+' · Esc — отмена';});
bind('close',()=>{capturing=null;options(back);});
}
function updateCastingHUD(){const live=controls.preferences.mode==='live';$('#hotbar').hidden=live;$('#live-casting').hidden=!live;$('#casting-mode').textContent=controls.key('toggle')+' · '+(live?'Составление':'Ячейки');$('#hud').classList.toggle('live-mode',live);if(!live){$('#casting-mode').style.bottom='105px';$('#prompt').style.bottom='123px';return;}
const recipe=controls.recipe(sim.s.research),program=S.compile(recipe),affordable=program&&A.canPay(sim.s.player.mana,program.cost);
$('#live-sequence').innerHTML=controls.elements.map(e=>`<span style="color:${mana(e).color}">${mana(e).glyph} ${mana(e).name}</span>`).join('<i>→</i>')||'<span class="dim">Наберите аспекты клавишами ниже</span>';
$('#live-cost').innerHTML=program?costs(recipe):'Пустой рецепт не расходует ману';$('#live-cost').classList.toggle('unaffordable',!!program&&!affordable);
$('#live-status').textContent=program?(affordable?'ЛКМ · применить':'Не хватает маны')+' · '+A.MODS.find(m=>m.id===controls.mod).name+' · '+program.cooldown.toFixed(2)+' с':'До пяти аспектов · выберите форму';
const formKey=JSON.stringify([controls.form,sim.s.research,controls.preferences.bindings]);if($('#live-forms').dataset.renderKey!==formKey){$('#live-forms').dataset.renderKey=formKey;$('#live-forms').innerHTML=A.FORMS.map((f,i)=>`<button data-live-form="${i}" class="${controls.form===f.id?'active':''}" ${f.level>sim.s.research?'disabled':''}>${controls.key('select'+(i+1))} · ${f.name}${f.level>sim.s.research?' 🔒':''}</button>`).join('');document.querySelectorAll('[data-live-form]').forEach(el=>el.onclick=()=>chooseCasting(Number(el.dataset.liveForm)));}
$('#aspect-keys').innerHTML=A.MANA.map(m=>`<span title="${mana(m.id).name}" style="color:${mana(m.id).color}"><b>${controls.key(m.id)}</b> ${mana(m.id).known?mana(m.id).name:'???'}</span>`).join('');
$('#live-help').textContent=controls.key('undo')+' удалить · '+controls.key('clear')+' очистить · '+controls.key('recall')+' прошлый каст · '+controls.key('modifier')+' модификатор';
$('#casting-mode').style.bottom=($('#live-casting').offsetHeight+30)+'px';$('#prompt').style.bottom=($('#live-casting').offsetHeight+76)+'px';
}

function toast(text){const el=document.createElement('div');el.className='toast';el.textContent=text;$('#toast').append(el);setTimeout(()=>el.remove(),4500);while($('#toast').children.length>3)$('#toast').firstChild.remove();}
function mana(id){const m=A.MANA.find(m=>m.id===id);const v=K.view(sim.s.knowledge,m);if(!v.known)v.name='Аспект '+['I','II','III','IV','V','VI','VII','VIII','IX','X'][A.MANA.indexOf(m)];return v;}
function spellName(spell){return (S.sequence(spell)||[]).map(e=>mana(e).name).join(' → ')+' · '+A.FORMS.find(f=>f.id===spell.form).name;}
function facts(element,kind){return K.entries(sim.s.knowledge,element,kind).map(f=>f.text).join(' ')||(kind==='source'?'Источник ещё не установлен.':'Действие ещё не наблюдалось. Испытайте разные формы и цели.');}
function readSave(){for(const key of [STORE,BACKUP]){try{const data=JSON.parse(localStorage.getItem(key));const migrated=A.migrateSave(data);if(migrated)return migrated;}catch{}}return null;}
function save(){if(!sessionStarted||!sim.s.started||mode==='title')return false;try{const prev=localStorage.getItem(STORE);if(prev){try{if(A.migrateSave(JSON.parse(prev)))localStorage.setItem(BACKUP,prev);}catch{}}localStorage.setItem(STORE,JSON.stringify(sim.s));saveFailed=false;return true;}catch{if(!saveFailed){toast('Не удалось записать сохранение. Проверьте свободное место и разрешение хранилища.');saveFailed=true;}return false;}}
function setMode(next){mode=next;sim.buildPreview=null;sim.active=next==='play';mouse.down=false;keys.clear();hud.hidden=next==='title'||next==='new';if(next==='play'){overlay.innerHTML='';updateHUD();}else{sim.events=sim.events.filter(e=>e.type!=='sound');if(next!=='title'&&next!=='new')updateHUD();}}
function bind(id,fn){document.getElementById(id)?.addEventListener('click',fn);}
function shell(title,body,wide=false,subtitle=''){overlay.innerHTML=`<div class="shade"><section class="panel ${wide?'wide':'narrow'}"><div class="panel-head"><div>${subtitle?`<div class="eyebrow">${subtitle}</div>`:''}<h2>${title}</h2></div><button class="small" id="close">Закрыть · Esc</button></div>${body}</section></div>`;bind('close',()=>setMode('play'));}
function title(){setMode('title');const saved=readSave();overlay.innerHTML=`<div class="title-screen"><div class="title-content"><div class="eyebrow">Мир — источник. Магия — язык.</div><h1>Палимпсест</h1><div class="subtitle">Живая магия</div><p>У мира больше нет единого голоса.<br>Научитесь слышать землю, воду и пространство.<br>И напишите его историю заново.</p><div class="title-actions">${saved?'<button class="primary" id="continue">Продолжить путешествие</button>':''}<button class="${saved?'':'primary'}" id="new">Начать новую историю</button><button id="guide">Как устроена магия</button><button id="settings">Настройки</button></div></div><div class="title-footer">ОДИНОЧНОЕ ПРИКЛЮЧЕНИЕ · ИССЛЕДУЙТЕ ИСТОЧНИКИ МАНЫ · ЭТАП VI</div></div>`;bind('continue',()=>{audio.start();sessionStarted=true;controls.resetJourney();sim=new Simulation(saved);renderer.camera={x:saved.player.x,y:saved.player.y};buildHUD();setMode('play');if(sim.s.relics.length<sim.level)relicScreen();});bind('new',newGame);bind('guide',()=>journal('title'));bind('settings',()=>options('title'));}
function newGame(){setMode('new');shell('Какой будет ваша история?',`<p>Вы — последний хранитель обсерватории. Восстановите пять печатей и остановите Переписчика, прежде чем он сотрёт живой мир.</p><div class="divider"></div><div class="stack"><button id="gentle"><b>Созерцание</b><br><span class="dim tiny">Мягче сражения. Больше пространства для экспериментов.</span></button><button class="primary" id="normal"><b>Равновесие</b><br><span class="tiny">Исследование, подготовка и опасные столкновения.</span></button><button id="hard"><b>Разлом</b><br><span class="dim tiny">Сильнее враги. Каждая ошибка расходует ресурсы.</span></button></div>${readSave()?'<p class="tiny" style="margin-top:18px">Новая история заменит текущее автосохранение.</p>':''}`);bind('close',title);for(const difficulty of ['gentle','normal','hard'])bind(difficulty,()=>{audio.start();sessionStarted=true;controls.resetJourney();sim=new Simulation(A.createState(31719+Math.floor(Math.random()*100000),difficulty));renderer.camera={x:sim.s.player.x,y:sim.s.player.y};buildHUD();setMode('play');try{localStorage.removeItem(BACKUP);localStorage.removeItem(STORE);}catch{}save();intro();});}
function intro(){setMode('intro');shell('Последняя обсерватория',`<p class="lore">«Не ищи силу внутри себя.<br>Посмотри, на чём ты стоишь».</p><div class="divider"></div><p>Так заканчивается дневник вашего учителя. Пять печатей погасли. За ними просыпается существо, которое умеет переписывать саму материю.</p><p style="margin-top:14px">Начните с простого: постойте на земле. Затем подойдите к воде справа от обсерватории. Посмотрите, как меняются запасы маны.</p><div class="divider"></div><p><span class="key">${['up','left','down','right'].map(a=>controls.key(a)).join('')}</span> движение &nbsp; <span class="key">ЛКМ</span> заклинание<br><span class="key">${[1,2,3,4].map(i=>controls.key('select'+i)).join('/')}</span> выбор &nbsp; <span class="key">${controls.key('editor')}</span> конструктор<br><span class="key">${controls.key('interact')}</span> взаимодействие &nbsp; <span class="key">${controls.key('journal')}</span> дневник</p><button class="primary" id="begin" style="margin-top:22px">Я слышу землю</button>`,'','Глава I · Найти голос');bind('begin',()=>setMode('play'));}
function buildHUD(){hud.innerHTML=`<div class="hud-top"><div class="brand">ПАЛИМПСЕСТ / ЖИВАЯ МАГИЯ</div><div class="row between tiny"><span id="hptext"></span><span id="shieldtext"></span></div><div class="health"><div id="hpbar"></div></div><div class="objective" id="objective"></div></div><div class="zone" id="zone"></div><div id="wall-inspect" class="wall-inspect" hidden></div><div class="hud-right"><div class="row"><button class="small" id="journal-btn">Дневник · J</button><button class="small" id="pause-btn">Ⅱ</button></div><div class="map-wrap"><canvas id="minimap" width="208" height="208"></canvas></div><div class="tiny dim" style="margin-top:7px" id="resources"></div></div><div class="mana-bank" id="mana-bank"></div><div class="hotbar" id="hotbar"></div><button id="casting-mode" class="small casting-mode"></button><section id="live-casting" class="live-casting" hidden><div id="live-sequence"></div><div id="live-forms"></div><div id="live-cost"></div><div id="live-status"></div><div id="aspect-keys"></div><div id="live-help"></div></section><div class="hud-help">ЛКМ · заклинание &nbsp; ПКМ · искра<br>Tab · конструктор &nbsp; M · карта<br>Пробел · рывок &nbsp; E · действие</div><div class="prompt" id="prompt" hidden></div><div class="bossbar" id="bossbar" hidden></div>`;bind('casting-mode',toggleCasting);bind('journal-btn',()=>journal());bind('pause-btn',pause);updateHUD();}
const tutorials=[['Слушайте землю','Постойте на почве, затем подойдите к воде справа от обсерватории. Цветные шкалы показывают сбор маны.'],['Первое слово','ЛКМ выпускает заклинание к курсору. Испытайте 3 заклинания. Цифры выбирают ячейку или форму. Режим магии переключается кнопкой над заклинаниями.'],['Соберите заклинание','Откройте конструктор. Наберите до пяти аспектов, выберите форму и модификатор, сохраните рецепт.'],['Измените мир','Снаряд воды создаёт воду на почве. Попробуйте вернуть сушу землёй. Нужно 3 преобразования.'],['Корни памяти','Идите на запад (влево) к первой печати. Печати нужны земля и ещё один аспект. Обследуйте окружение. E показывает требуемые сосуды.']];
function objective(){const s=sim.s;if(s.won)return ['Мир обрёл новый голос','История завершена. Вы можете продолжать исследование и эксперименты.'];if(s.tutorial<5){const t=tutorials[s.tutorial]||tutorials[4];return [t[0],t[1].replace('Откройте конструктор.', 'Конструктор: '+controls.key('editor')+'.').replace('E показывает',controls.key('interact')+' показывает')];}if(sim.level===5)return ['Последняя страница','Вернитесь к Первому разлому к северу от обсерватории. Подготовьте запас всех стихий и нажмите E.'];const target=s.shrines.find(x=>x.status==='active')||s.shrines.find(x=>x.status==='cleared')||s.shrines.find(x=>x.status!=='restored');return [target.name,target.status==='active'?'Победите стражей. Используйте окружение для сбора маны.':target.status==='cleared'?'Стражи повержены. Подойдите к печати и нажмите E.':`Пробудите печать: ${mana(target.element).name} 25 + ${mana(target.second).name} 15. Карта: ${controls.key('map')}.`];}
function FName(wall){return A.fortifications.MATERIALS[wall.material].name;}
function skyText(){const e=sim.exposure||A.daylight.exposure(sim.s.tiles,sim.s.player,sim.s.time),sun=e.sun;return `День ${sun.day} · ${sun.clock} · ${sun.phase}<span class="sky-position">${sun.daylight?(e.shaded?'В отбрасываемой тени':'Под прямым солнцем'):'Солнце за горизонтом'}</span>`;}
function updateHUD(){if(!$('#hpbar'))return;const s=sim.s,p=s.player,current=controls.preferences.mode==='live'?controls.recipe(s.research):s.spells[s.selected];sim.buildPreview=mode==='play'&&S.compile(current)?.nodes.some(n=>n.id==='barrier')?sim.wallPlan(current,renderer.screenToWorld(mouse.x,mouse.y)):null;$('#journal-btn').textContent='Дневник · '+controls.key('journal');$('.hud-help').textContent='ЛКМ · заклинание / ПКМ · искра — '+controls.key('editor')+' конструктор · '+controls.key('map')+' карта · '+controls.key('dash')+' рывок · '+controls.key('interact')+' действие';$('#hptext').textContent=`ЖИЗНЬ  ${Math.ceil(p.hp)} / ${p.maxHp}`;$('#shieldtext').textContent=p.shield>0?'ЩИТ '+Math.ceil(p.shield):'';$('#hpbar').style.width=Math.max(0,p.hp/p.maxHp*100)+'%';const [title,desc]=objective();$('#objective').innerHTML=`<span class="eyebrow" style="font-size:9px;letter-spacing:2px">ПЕЧАТИ ${sim.level} / 5</span><strong>${title}</strong><p>${desc}</p>`;const b=A.biome(p.x/40,p.y/40),nearCamp=Math.hypot(p.x-2100,p.y-2140)<310;$('#zone').innerHTML=(nearCamp?'Тихая обсерватория':A.SHRINES[b].biome)+`<small>${['СОЗЕРЦАНИЕ','РАВНОВЕСИЕ','РАЗЛОМ'][['gentle','normal','hard'].indexOf(s.difficulty)]} · ${Math.floor(s.time/60)} МИН</small><div class="sky-clock" id="sky-clock">${skyText()}</div>`;const point=renderer.screenToWorld(mouse.x,mouse.y),wi=Math.floor(point.y/40)*104+Math.floor(point.x/40),wall=s.walls[wi];$('#wall-inspect').hidden=mode!=='play'||!wall;if(wall){$('#wall-inspect').textContent=FName(wall)+' · '+Math.ceil(wall.hp)+' / '+wall.maxHp;$('#wall-inspect').style.left=Math.max(8,Math.min(innerWidth-240,mouse.x+14))+'px';$('#wall-inspect').style.top=Math.max(8,mouse.y-52)+'px';}$('#resources').textContent=`✧ ${s.shards} осколков · Исследования ${s.research}/3`;
$('#mana-bank').innerHTML=A.MANA.map(raw=>{const m=mana(raw.id),flow=(sim.rates[m.id]||0)>0,pulse=(manaPulse[m.id]||0)>performance.now();return `<div class="mana ${flow||pulse?'gaining':''}" style="--c:${m.color}" title="${m.name}"><div class="row"><i></i><span>${m.known?(m.id==='space'?'Простр.':m.name):'???'}</span><span class="mana-value">${Math.floor(p.mana[m.id])}${flow?' ↑':pulse?' +':''}</span></div><div class="mana-track"><div class="mana-fill" style="width:${p.mana[m.id]/p.cap*100}%"></div></div></div>`;}).join('');
$('#hotbar').innerHTML=s.spells.map((spell,i)=>{const m=mana(spell.element),f=A.FORMS.find(f=>f.id===spell.form);return `<button class="slot ${s.selected===i?'active':''}" data-slot="${i}" style="--c:${m.color}" title="${spellName(spell)}"><span class="number">${controls.key('select'+(i+1))}</span><div class="glyph ${S.sequence(spell).length>1?'multi-glyph':''}">${S.sequence(spell).map(e=>`<span style="color:${mana(e).color}">${mana(e).glyph}</span>`).join('')}</div><div class="name">${f.glyph} ${f.name==='Воплощение'?'Я':f.name} · ${S.sequence(spell).length} асп.</div></button>`;}).join('');document.querySelectorAll('[data-slot]').forEach(el=>el.onclick=()=>{chooseCasting(Number(el.dataset.slot));});
updateCastingHUD();const n=sim.nearby();let prompt='';if(n?.kind==='camp')prompt='E · Обсерватория — лечение, исследования и точка возврата';if(n?.kind==='gate')prompt=sim.level===5?'E · Открыть последнюю страницу':'Первый разлом · Восстановите пять печатей';if(n?.kind==='shrine'){const sh=n.shrine;prompt=sh.status==='restored'?'E · Отдохнуть у печати':sh.status==='active'?'Стражей осталось: '+s.enemies.filter(e=>e.guard===n.index).length:sh.status==='cleared'?'E · Восстановить печать':`E · Пробудить: ${mana(sh.element).name} 25 + ${mana(sh.second).name} 15`;}$('#prompt').hidden=!prompt;$('#prompt').textContent=prompt.replace(/^E ·/,controls.key('interact')+' ·');const boss=s.boss;$('#bossbar').hidden=!boss;if(boss)$('#bossbar').innerHTML=`ПЕРЕПИСЧИК · Защита: ${mana(boss.ward).name}<div class="health"><div style="width:${Math.max(0,boss.hp/boss.maxHp*100)}%"></div></div><span class="tiny">${Math.ceil(boss.hp)} / ${boss.maxHp} · Меняйте стихии</span>`;
}
function costs(spell){return Object.entries(A.cost(spell)||{}).map(([e,n])=>{const m=mana(e);return `<span class="cost" style="--c:${m.color};color:${m.color}"><i></i>${m.name} ${n}</span>`;}).join('');}
function spellbook(){setMode('editor');editor=S.normalize(controls.preferences.mode==='live'&&controls.recipe(sim.s.research)||sim.s.spells[sim.s.selected]);drawEditor();}
function drawEditor(){
const slot=sim.s.selected,allowed=r=>r.level<=sim.s.research,program=S.compile(editor),full=editor.elements.length>=S.MAX_ASPECTS;
const preview=program?program.nodes.map(n=>n.kind==='reaction'?(sim.s.knowledge.facts.includes('reaction:'+n.id)?S.REACTIONS[n.id].name:'Неизученное сочетание'):mana(n.element).name).join(' → '):'Добавьте хотя бы один аспект.';
shell('Мастерская заклинаний',`<div class="row between grammar-intro"><p>Добавляйте аспекты слева направо. Порядок меняет действие; повтор усиливает с убывающей отдачей.</p><span class="tag">ЯЧЕЙКА ${slot+1} / 4</span></div>
<div class="sequence-heading"><span class="section-label">Последовательность · ${editor.elements.length} / 5</span><button class="small" id="clear-sequence" ${editor.elements.length?'':'disabled'}>Очистить</button></div>
<div class="sequence" aria-label="Последовательность аспектов">${editor.elements.map((e,i)=>{const m=mana(e);return `<div class="sequence-token" style="--c:${m.color}"><div><span class="dim">${i+1}.</span> <b>${m.glyph} ${m.name}</b></div><div class="sequence-tools"><button data-left="${i}" aria-label="Аспект ${i+1} влево" ${i?'':'disabled'}>←</button><button data-remove="${i}" aria-label="Удалить аспект ${i+1}">×</button><button data-right="${i}" aria-label="Аспект ${i+1} вправо" ${i<editor.elements.length-1?'':'disabled'}>→</button></div></div>`;}).join('')||'<p class="sequence-empty">Выберите аспекты ниже — одиночный рецепт тоже работает.</p>'}</div>
<div class="spell-grid"><div><div class="section-label">Форма применения</div><div class="stack">${A.FORMS.map(f=>`<button class="option ${editor.form===f.id?'active':''}" data-form="${f.id}" ${allowed(f)?'':'disabled'}><b>${f.glyph} ${f.name}${allowed(f)?'':' · 🔒'}</b><span>${allowed(f)?f.desc:'Исследование I'}</span></button>`).join('')}</div></div>
<div><div class="section-label">Добавить аспект ${full?'· лимит достигнут':''}</div><div class="options">${A.MANA.map(raw=>{const m=mana(raw.id);return `<button class="option" data-element="${m.id}" ${full?'disabled':''}><b style="color:${m.color}">+ ${m.glyph} ${m.name}</b><span>${Math.floor(sim.s.player.mana[m.id])} / ${sim.s.player.cap} маны</span></button>`;}).join('')}</div></div>
<div><div class="section-label">Модификатор</div><div class="stack">${A.MODS.map(m=>`<button class="option ${editor.mod===m.id?'active':''}" data-mod="${m.id}" ${allowed(m)?'':'disabled'}><b>${m.name}${allowed(m)?'':' · 🔒'}</b><span>${allowed(m)?m.desc:'Исследование '+['','I','II','III'][m.level]}</span></button>`).join('')}</div></div></div>
<div class="recipe"><div class="recipe-preview"><h3>${preview}</h3><p class="tiny">${program?'Задержка между применениями: '+program.cooldown.toFixed(2)+' с. Свойства открываются при испытании.':'Пустой рецепт нельзя записать или применить.'}</p></div><div class="row between recipe-actions"><div class="recipe-costs">${costs(editor)}${program&&!A.canPay(sim.s.player.mana,program.cost)?'<span class="tiny dim">Запасов пока не хватает. Рецепт можно сохранить.</span>':''}</div><button class="primary" id="equip" ${program?'':'disabled'}>Записать в ячейку ${slot+1}</button></div></div>`,true,'Арканика / Грамматика');
$('.panel').classList.add('grammar-panel');
const redraw=()=>{editor.element=editor.elements[0];drawEditor();};
document.querySelectorAll('[data-element]').forEach(el=>el.onclick=()=>{if(editor.elements.length<S.MAX_ASPECTS){editor.elements.push(el.dataset.element);redraw();}});
for(const attr of ['form','mod'])document.querySelectorAll('[data-'+attr+']').forEach(el=>el.onclick=()=>{editor[attr]=el.dataset[attr];drawEditor();});
document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{editor.elements.splice(Number(el.dataset.remove),1);redraw();});
for(const [attr,step] of [['left',-1],['right',1]])document.querySelectorAll('[data-'+attr+']').forEach(el=>el.onclick=()=>{const i=Number(el.dataset[attr]),j=i+step;if(j>=0&&j<editor.elements.length){[editor.elements[i],editor.elements[j]]=[editor.elements[j],editor.elements[i]];redraw();}});
bind('clear-sequence',()=>{editor.elements=[];redraw();});
bind('equip',()=>{const recipe=S.normalize(editor);if(!recipe)return;sim.s.spells[slot]=recipe;if(controls.preferences.mode==='live'){controls.elements=[...recipe.elements];controls.form=recipe.form;controls.mod=recipe.mod;}if(sim.s.tutorial===2)sim.s.tutorial=3;save();setMode('play');toast('Записано: '+spellName(recipe));});
}
function journal(back='play'){setMode('journal');shell('Полевой дневник',`<div class="journal-grid"><div class="card"><h3>Небо движется</h3><p>День сменяется ночью за восемь минут игрового времени. Деревья и скалы отбрасывают движущиеся тени. Заклинания, меняющие окружение, меняют и освещение. Часы над миром помогут сравнить наблюдения; пауза останавливает время.</p></div><div class="card"><h3>Мир — ваш резервуар</h3><p>У маны нет общего восстановления. Стрелка ↑ означает сбор из окружения; + — отклик на событие. Вместимость сосуда: ${sim.s.player.cap}.</p></div><div class="card"><h3>Открыто ${sim.s.knowledge.known.length} / ${A.MANA.length} аспектов</h3><p>В записях учителя остались земля, вода и воздух. Остальное узнайте сами: ищите источники, пробуйте формы, меняйте окружение. Удачные реакции и сопротивления записываются автоматически.</p><p>Наблюдений: ${sim.s.knowledge.facts.length}. Неизвестная реакция не означает, что её нет.</p></div><div class="card"><h3>Язык сочетаний</h3><p>В конструкторе можно собрать от одного до пяти аспектов. Соседние аспекты иногда образуют особую реакцию. Меняйте порядок, пробуйте разные формы. Повторы требуют полной стоимости, но дают всё меньше силы.</p><p>${sim.s.knowledge.facts.filter(id=>K.FACTS[id].kind==='reaction').map(id=>K.FACTS[id].text).join('<br><br>')||'Особые сочетания пока не наблюдались.'}</p></div>${A.MANA.map(raw=>{const m=mana(raw.id);return `<div class="card"><h3 style="color:${m.color}">${m.glyph} ${m.name}</h3>${m.known?`<p><b>Источники</b><br>${facts(m.id,'source')}</p><p><b>Наблюдения</b><br>${facts(m.id,'effect')}</p>`:'<p>Пустая страница. Этот сосуд ещё ни на что не откликнулся.</p>'}</div>`;}).join('')}<div class="card"><h3>Печати и исследования</h3><p>Пробудите печать за указанную ману, победите стражей и нажмите E ещё раз. Каждая печать даёт реликвию и 12 осколков. Исследуйте формы в обсерватории.</p></div><div class="card"><h3>Бой и возвращение</h3><p>ПКМ — бесплатная слабая искра. Пробел — рывок за воздух. В обсерватории можно восстановить здоровье. Гибель отнимает 20% осколков, но сохраняет открытия и печати. Повторная встреча не обновляет уже полученную событийную награду.</p></div><div class="card"><h3>Управление</h3><p>${['up','left','down','right'].map(a=>controls.key(a)).join('')} / стрелки — движение<br>ЛКМ — заклинание, ПКМ — искра<br>Цифры / колесо — ячейка или форма<br>Режим магии и клавиши — в настройках<br>${controls.key('dash')} — рывок<br>${controls.key('interact')} — действие, ${controls.key('editor')} — конструктор<br>${controls.key('map')} — карта, ${controls.key('journal')} — дневник, Esc — пауза<br>F11 — полный экран</p></div><div class="card"><h3>Записки хранителей</h3><p>${sim.s.shrines.filter(s=>s.status==='restored').map(s=>'«'+s.text+'»').join('<br><br>')||'Восстанавливайте печати, чтобы услышать голоса прежних хранителей.'}</p></div></div>`,true,'Знание меняет материю');bind('close',()=>back==='title'?title():setMode('play'));returnTo=back;}
function pause(){setMode('pause');save();shell('Между страницами',`<p>Мир замер. Путешествие ${saveFailed?'не удалось сохранить':'сохранено'}.</p><div class="stats"><div><b>${sim.level}/5</b><span>печатей</span></div><div><b>${sim.s.stats.casts}</b><span>заклинаний</span></div><div><b>${Math.floor(sim.s.time/60)}</b><span>минут в мире</span></div></div><div class="stack"><button class="primary" id="resume">Продолжить</button><button id="savepause">Сохранить сейчас</button><button id="settings">Настройки</button><button id="book">Полевой дневник</button><button id="menu">Главное меню</button></div>`);bind('resume',()=>setMode('play'));bind('savepause',()=>toast(save()?'Путешествие сохранено.':'Не удалось сохранить.'));bind('settings',()=>options('pause'));bind('book',()=>journal());bind('menu',()=>{save();title();});}
function options(back){setMode('settings');returnTo=back;shell('Настройки',`<div class="settings-row"><span>Громкость эффектов</span><input id="volume" aria-label="Громкость эффектов" type="range" min="0" max="1" step=".01" value="${settings.volume}"></div><div class="settings-row"><span>Музыка</span><input id="music" aria-label="Громкость музыки" type="range" min="0" max="1" step=".01" value="${settings.music}"></div><div class="settings-row"><label for="shake">Дрожание камеры</label><input id="shake" type="checkbox" ${settings.shake?'checked':''}></div><div class="settings-row"><label for="particles">Атмосферные частицы</label><input id="particles" type="checkbox" ${settings.particles?'checked':''}></div><div class="divider"></div><button id="key-settings">Клавиши и режим магии</button> <button id="fullscreen">Полный экран · F11</button><p class="tiny" style="margin-top:16px">Все действия доступны с русской и английской раскладкой. Игра автоматически ставится на паузу при переключении окна. Настройки сохраняются сразу.</p>`);for(const id of ['volume','music','shake','particles'])$('#'+id).oninput=e=>{settings[id]=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);audio.volume=settings.volume;audio.music=settings.music;audio.start();try{localStorage.setItem(OPTIONS,JSON.stringify(settings));}catch{}};bind('key-settings',()=>controlsScreen(back));bind('fullscreen',fullscreen);bind('close',()=>back==='title'?title():pause());}
function fullscreen(){if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});else document.documentElement.requestFullscreen().catch(()=>toast('Полный экран доступен через F11 в настольной версии.'));}
function map(){setMode('map');shell('Атлас расколотого мира',`<canvas id="large-map" class="map-large" width="728" height="728"></canvas><div class="map-legend"><span>● Вы</span><span style="color:#e1ba7b">● Печать</span><span style="color:#a5e3b8">● Восстановлена</span><span style="color:#b29dd5">■ Первый разлом</span></div><p class="tiny" style="text-align:center;margin-top:12px">Непосещённые земли скрыты. Древние печати нанесены по записям учителя.</p>`,true,'Пять голосов / Один мир');renderer.map($('#large-map'),sim,true);}
function camp(){setMode('camp');const n=sim.s.research,price=8+n*8;const unlocks=['Печать и Протяжение','Эхо и Жатва','Связь'];shell('Тихая обсерватория',`<p>Здесь можно перевести дыхание. Здоровье восстановлено; эта обсерватория стала вашей точкой возврата.</p><div class="divider"></div><div class="eyebrow">ИССЛЕДОВАНИЯ ${n}/3 · ✧ ${sim.s.shards} ОСКОЛКОВ</div><h3>${n<3?unlocks[n]:'Все руны расшифрованы'}</h3><p style="margin-top:12px">${['Научитесь оставлять длительную область магии и увеличивать дальность заклинаний.','Повторяйте заклинания эхом или возвращайте ману стихии за поверженных врагов.','Передавайте действие заклинания двум соседним врагам.','Все формы и модификаторы расшифрованы. Продолжайте открывать аспекты и испытывать сочетания.'][n]}</p>${n<3?`<button class="primary" id="research" style="margin-top:20px" ${sim.s.shards<price?'disabled':''}>Расшифровать · ${price} осколков</button>`:''}<div class="divider"></div><p class="tiny">Осколки остаются после врагов и восстановления печатей. У отдыха нет платы, но он не заполняет ману: источники расположены вокруг обсерватории.</p>`);bind('research',()=>{if(sim.research()){processEvents();camp();}});}
function relicScreen(index){setMode('relic');const s=index===undefined?sim.s.shrines.filter(s=>s.status==='restored').at(-1):sim.s.shrines[index];const choices=A.RELICS.filter(r=>!sim.has(r.id));shell('Память возвращается',`<p class="lore">«${s.text}»</p><div class="divider"></div><p style="margin-bottom:20px">Печать «${s.name}» восстановлена. Получено 12 осколков. Выберите один постоянный дар:</p><div class="grid">${choices.map(r=>`<div class="card"><h3>${r.name}</h3><p>${r.desc}</p><button class="primary" data-relic="${r.id}">Принять дар</button></div>`).join('')}</div>`,true,'Печать '+sim.level+' / 5');$('#close').hidden=true;document.querySelectorAll('[data-relic]').forEach(el=>el.onclick=()=>{if(sim.chooseRelic(el.dataset.relic)){save();setMode('play');audio.fx('shrine');}});}
function finalReady(){setMode('finalReady');shell('Последняя страница',`<p class="lore">«Сохранить мир — не значит оставить его прежним».</p><div class="divider"></div><p>Пять голосов звучат вместе. Теперь вы можете войти в спор с Переписчиком.</p><p style="margin-top:12px">Его защита меняется: огонь, тень, земля. Вода сильнее огня, свет сильнее тени, воздух сильнее земли. Не стойте на месте: на последней фазе разлом ускоряется.</p><p style="margin-top:12px">Заполните сосуды, подготовьте лечение и несколько боевых стихий. При поражении можно попробовать снова.</p><button class="primary" id="fight" style="margin-top:22px">Дать миру новый голос</button>`);bind('fight',()=>{setMode('play');sim.startBoss();});}
function victory(){setMode('victory');save();shell('Не конец. Начало.',`<p class="lore">Переписчик умолк.<br>Но мир не вернулся к тому, каким был.<br>Он стал тем, что вы научились создавать.</p><div class="divider"></div><p>Земля удерживает память. Вода даёт ей движение. Даже тень нашла место на новой странице. Вы восстановили пять печатей — и вернули миру право меняться.</p><div class="stats"><div><b>${Math.floor(sim.s.time/60)}:${String(Math.floor(sim.s.time%60)).padStart(2,'0')}</b><span>время путешествия</span></div><div><b>${sim.s.stats.casts}</b><span>заклинаний</span></div><div><b>${sim.s.stats.transforms}</b><span>изменений мира</span></div></div><p class="tiny">Палимпсест · Живая магия<br>Оригинальная идея системы разных источников маны — автор проекта.<br>Код, графика и процедурный звук созданы для этой игры.</p><button class="primary" id="wander" style="margin-top:22px">Остаться в этом мире</button>`,'','Пять голосов обрели гармонию');bind('wander',()=>setMode('play'));}
function processEvents(){const events=sim.events.splice(0),discoveries=events.filter(e=>e.type==='discovery'),fresh=[...new Set(discoveries.filter(e=>e.fresh).map(e=>mana(e.element).name))];if(fresh.length)toast('Новый аспект: '+fresh.join(', ')+'. Запись в дневнике · J');else if(discoveries.length)toast('Новое наблюдение в дневнике · J');for(const e of events){if(e.type==='mana')manaPulse[e.element]=performance.now()+1400;if(e.type==='notice')toast(e.text);if(e.type==='sound')audio.fx(e.name,e.element);if(e.type==='save')save();if(e.type==='camp')camp();if(e.type==='restored')relicScreen(e.index);if(e.type==='finalReady')finalReady();if(e.type==='victory')victory();if(e.type==='death'){setMode('death');shell('Нить не оборвалась',`<p class="lore">Обсерватория помнит дорогу домой.</p><div class="divider"></div><p>Вы вернулись к последнему месту отдыха. Потеряно ${e.loss} осколков. Печати, руны и реликвии сохранены.</p><p style="margin-top:12px">Пополните базовые сосуды, испытайте защитные формы и используйте рывок за воздух. Обсерватория восстановит здоровье.</p><button class="primary" id="return" style="margin-top:22px">Продолжить историю</button>`);bind('return',()=>setMode('play'));}}}
function inputVector(){return controls.vector(keys);}
window.addEventListener('keydown',e=>{
if(capturing){e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){controlsScreen(returnTo);return;}if(controls.rebind(capturing,e.code)){saveControls();controlsScreen(returnTo);}else $('#capture-hint').textContent='Эта клавиша зарезервирована. Выберите букву, цифру, знак, Tab, Enter, Del, Backspace или пробел.';return;}
const action=controls.action(e.code);if(mode==='play'&&(['Tab','Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Backspace'].includes(e.code)||action)||mode==='editor'&&action==='editor')e.preventDefault();if(e.repeat||e.ctrlKey||e.altKey||e.metaKey)return;
if(e.code==='Escape'){if(mode==='play')pause();else if(mode==='title'||mode==='relic'){}else if(mode==='new')title();else if(mode==='controls')options(returnTo);else if(mode==='settings')returnTo==='title'?title():pause();else if(mode==='journal'&&returnTo==='title')title();else setMode('play');return;}
if(e.code==='F11'&&!navigator.userAgent.includes('Electron')){e.preventDefault();fullscreen();return;}
if(mode!=='play'){if(action==='editor'&&mode==='editor'||action==='map'&&mode==='map'||action==='journal'&&mode==='journal'&&returnTo!=='title')setMode('play');return;}
keys.add(e.code);
if(action==='toggle'){toggleCasting();return;}
if(action?.startsWith('select')){chooseCasting(Number(action.at(-1))-1);return;}
if(controls.preferences.mode==='live'){
let changed=true;
if(S.IDS.includes(action)){if(!controls.append(action))toast('В рецепте уже пять аспектов. Удалите последний или очистите рецепт.');}
else if(action==='undo')controls.elements.pop();
else if(action==='clear')controls.elements=[];
else if(action==='recall'){if(!controls.recall(sim.s.research))toast('Пока нет применённого рецепта для повтора.');}
else if(action==='modifier')controls.cycle(sim.s.research);
else changed=false;
if(changed){mouse.down=false;updateHUD();return;}
}
if(action==='editor')spellbook();if(action==='journal')journal();if(action==='map')map();if(action==='interact'){sim.interact();processEvents();}
if(action==='dash'){let v=inputVector();if(!v.x&&!v.y){const target=renderer.screenToWorld(mouse.x,mouse.y);v={x:target.x-sim.s.player.x,y:target.y-sim.s.player.y};}sim.dash(v.x,v.y);processEvents();}
});
window.addEventListener('keyup',e=>keys.delete(e.code));canvas.addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;});canvas.addEventListener('mousedown',e=>{if(mode!=='play')return;audio.start();mouse.x=e.clientX;mouse.y=e.clientY;if(e.button===0){mouse.down=true;castCurrent();processEvents();}if(e.button===2&&sim.cooldown<=0){const p=sim.s.player,t=renderer.screenToWorld(mouse.x,mouse.y),d=Math.hypot(t.x-p.x,t.y-p.y)||1;sim.projectiles.push({x:p.x,y:p.y,vx:(t.x-p.x)/d*390,vy:(t.y-p.y)/d*390,life:.75,r:4,spell:{element:'air',form:'bolt',mod:'plain'},power:1/3,color:'#d6e6ce',enemy:false});sim.cooldown=.6;audio.fx('cast','air');}});window.addEventListener('mouseup',()=>mouse.down=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();if(mode==='play'){const forms=A.FORMS.filter(f=>f.level<=sim.s.research);if(controls.preferences.mode==='live'){const i=forms.findIndex(f=>f.id===controls.form);chooseCasting(A.FORMS.indexOf(forms[(i+(e.deltaY>0?1:forms.length-1))%forms.length]));}else chooseCasting((sim.s.selected+(e.deltaY>0?1:3))%4);}},{passive:false});window.addEventListener('blur',()=>{keys.clear();mouse.down=false;if(mode==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')pause();});window.addEventListener('beforeunload',()=>{if(mode!=='title')save();});
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(mode==='play'){sim.update(dt,inputVector());if(mouse.down)castCurrent();processEvents();}renderer.draw(sim,dt,mode==='title'||mode==='new',settings);audio.update(dt);uiTimer+=dt;mapTimer+=dt;if(mode==='play'&&uiTimer>.12){uiTimer=0;updateHUD();}if(!hud.hidden&&mapTimer>.4){mapTimer=0;const mapCanvas=$('#minimap');if(mapCanvas)renderer.map(mapCanvas,sim);}requestAnimationFrame(frame);}
title();requestAnimationFrame(frame);console.info('PALIMPSEST_READY');
})();
