'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),A=require('../core.js'),H=A.archives,Simulation=require('../simulation.js');
function scene(){const s=A.createState();s.worldPopulated=s.magesPopulated=s.ecology.populated=true;for(const id of ['earth','water','air'])s.player.mana[id]=60;return new Simulation(s);}
function step(sim,n){for(let i=0;i<Math.ceil(n/.025);i++)sim.update(.025);}
function visit(sim,p){Object.assign(sim.s.player,{x:p.x,y:p.y});sim.interact();}
function accept(sim){visit(sim,H.NERA);assert.ok(H.choose(sim,'archive-accept'));}
function cast(sim,i,element){const p=H.point(i);Object.assign(sim.s.player,{x:p.x-80,y:p.y});sim.cooldown=0;assert.ok(sim.cast(p,false,{element,form:'bolt',mod:'plain'}));step(sim,.65);}
function recover(sim){accept(sim);visit(sim,H.RECORDS[0]);cast(sim,H.INLET,'earth');for(const i of H.BASIN)cast(sim,i,'earth');visit(sim,H.RECORDS[1]);for(const i of H.CHANNEL)cast(sim,i,'water');cast(sim,H.DESK,'earth');step(sim,3.1);visit(sim,H.RECORDS[2]);assert.equal(sim.s.archive.stage,'interpret');}
test('archive stations are reachable on 40 seeds and preserve constructed walls',()=>{for(let seed=0;seed<40;seed++){const s=A.createState(seed);s.worldPopulated=s.magesPopulated=s.ecology.populated=true;new Simulation(s);for(const p of [H.NERA,...H.RECORDS,...H.CHANNEL.map(H.point),H.point(H.INLET)])assert.ok(A.reachable(s.tiles,53*104+52,Math.floor(p.y/40)*104+Math.floor(p.x/40)),`seed ${seed}`);assert.ok(A.validSave(s));}const s=A.createState();s.tiles[H.INLET]='barrier';s.walls[H.INLET]={hp:80,maxHp:80,material:'earth'};new Simulation(s);assert.equal(s.tiles[H.INLET],'barrier');});
test('unaccepted archive is quiet, cannot be bypassed at the seal or remotely accepted',()=>{const sim=scene();assert.equal(H.choose(sim,'archive-accept'),false);sim.s.tiles[H.BASIN[1]]='soil';step(sim,5);assert.equal(sim.s.tiles[H.BASIN[1]],'soil');visit(sim,{x:1060,y:940});assert.equal(sim.s.shrines[1].status,'dormant');assert.equal(sim.s.player.mana.water,60);assert.equal(sim.s.enemies.length,0);visit(sim,H.RECORDS[0]);assert.deepEqual(sim.s.archive.records,[]);});
test('active inlet refloods a dry room, while sealing the inlet lets paid earth casts preserve it',()=>{const sim=scene();accept(sim);cast(sim,H.BASIN[1],'earth');assert.equal(sim.s.tiles[H.BASIN[1]],'soil');step(sim,4.1);assert.equal(sim.s.tiles[H.BASIN[1]],'water');cast(sim,H.INLET,'earth');for(const i of H.BASIN)cast(sim,i,'earth');step(sim,5);assert.ok(H.ready(sim.s,'testimony'));assert.equal(sim.s.archive.surge,0);});
test('the west record needs the entire safe floor and a closed inlet, not just proximity',()=>{const sim=scene();accept(sim);visit(sim,H.RECORDS[1]);assert.deepEqual(sim.s.archive.records,[]);sim.s.tiles[H.INLET]='soil';for(const i of H.BASIN)sim.s.tiles[i]='soil';for(const tile of ['water','ice','steam','fire','lava','barrier']){sim.s.tiles[H.BASIN[0]]=tile;assert.equal(H.ready(sim.s,'testimony'),false);}sim.s.tiles[H.BASIN[0]]='soil';visit(sim,H.RECORDS[1]);assert.deepEqual(sim.s.archive.records,['testimony']);visit(sim,H.RECORDS[1]);assert.equal(sim.s.archive.records.length,1);});
test('three real water casts power the lift, one lost cup resets it, and wet desk blocks reading',()=>{const sim=scene();accept(sim);for(const i of H.CHANNEL)cast(sim,i,'water');step(sim,3.1);assert.equal(sim.s.archive.lift,3);assert.equal(H.ready(sim.s,'countermand'),false);cast(sim,H.DESK,'earth');assert.ok(H.ready(sim.s,'countermand'));cast(sim,H.CHANNEL[1],'earth');assert.equal(sim.s.archive.lift,0);assert.equal(H.ready(sim.s,'countermand'),false);cast(sim,H.CHANNEL[1],'water');step(sim,3.1);visit(sim,H.RECORDS[2]);assert.ok(sim.s.archive.records.includes('countermand'));});
test('temporary frost closes the real inlet only until thaw, then water returns',()=>{const sim=scene();accept(sim);sim.transform(H.point(H.INLET).x,H.point(H.INLET).y,20,{elements:['water','air'],form:'bolt',mod:'plain'});assert.equal(sim.s.tiles[H.INLET],'ice');sim.s.tiles[H.BASIN[1]]='soil';step(sim,1);assert.equal(sim.s.tiles[H.BASIN[1]],'soil');step(sim,12);assert.equal(sim.s.tiles[H.INLET],'water');assert.equal(sim.s.tiles[H.BASIN[1]],'water');});
test('water apparatus changes do not count as player casts, transformations, blood or death',()=>{const sim=scene();accept(sim);sim.s.tiles[H.BASIN[0]]='soil';const transforms=sim.s.stats.transforms;step(sim,5);assert.equal(sim.s.stats.transforms,transforms);assert.equal(sim.s.stats.casts,0);assert.equal(sim.s.player.mana.blood,0);assert.equal(sim.s.player.mana.death,0);assert.equal(sim.s.terrainCredit[H.BASIN[0]],undefined);});
test('complete paid spell route collects three records; wrong theories keep evidence and allow retry',()=>{const sim=scene();recover(sim);assert.ok(sim.s.stats.casts>=8);assert.equal(sim.s.stats.kills,0);assert.equal(H.choose(sim,'archive-rewrite'),false);visit(sim,H.NERA);const before=JSON.stringify(sim.s.archive);assert.equal(H.choose(sim,'archive-flood'),false);assert.equal(H.choose(sim,'archive-invasion'),false);assert.equal(JSON.stringify(sim.s.archive),before);assert.ok(H.choose(sim,'archive-rewrite'));assert.equal(sim.s.archive.stage,'restore');});
test('second seal pays atomically, grants one relic and keeps the remaining campaign accessible',()=>{const sim=scene();recover(sim);visit(sim,H.NERA);H.choose(sim,'archive-rewrite');sim.s.player.mana.water=24;sim.s.player.mana.air=60;visit(sim,{x:1060,y:940});assert.equal(sim.s.archive.stage,'restore');assert.equal(sim.s.player.mana.air,60);sim.s.player.mana.water=60;visit(sim,{x:1060,y:940});assert.equal(sim.s.archive.stage,'done');assert.equal(sim.s.player.mana.water,35);assert.equal(sim.s.player.mana.air,45);assert.equal(sim.s.shards,12);assert.equal(sim.s.shrines[1].status,'restored');assert.ok(sim.chooseRelic('roots'));assert.equal(sim.chooseRelic('roots'),false);visit(sim,{x:1060,y:940});assert.equal(sim.s.shards,12);const sh=sim.s.shrines[2];sim.s.player.mana.fire=sim.s.player.mana.earth=60;visit(sim,{x:(sh.x+.5)*40,y:(sh.y+.5)*40});assert.equal(sh.status,'active');assert.ok(sim.s.enemies.some(e=>e.guard===2));assert.ok(A.validSave(sim.s));});
test('save/reload preserves pressure timer, lift, spells, records and terrain without reseeding',()=>{const sim=scene();accept(sim);visit(sim,H.RECORDS[0]);for(const i of H.CHANNEL)sim.s.tiles[i]='water';step(sim,1.25);sim.s.tiles[H.BASIN[1]]='soil';const saved=A.migrateSave(sim.s),loaded=new Simulation(saved);assert.deepEqual(loaded.s.archive,sim.s.archive);assert.deepEqual(loaded.s.tiles,sim.s.tiles);step(sim,3);step(loaded,3);assert.deepEqual(loaded.s.archive,sim.s.archive);assert.equal(loaded.s.tiles[H.BASIN[1]],'water');});
test('death and pause preserve records and closed inlet; pause stops pressure',()=>{const sim=scene();accept(sim);visit(sim,H.RECORDS[0]);cast(sim,H.INLET,'earth');sim.die();assert.deepEqual(sim.s.archive.records,['catalogue']);assert.equal(sim.s.tiles[H.INLET],'soil');sim.s.tiles[H.INLET]='water';sim.s.tiles[H.BASIN[0]]='soil';sim.active=false;step(sim,10);assert.equal(sim.s.tiles[H.BASIN[0]],'soil');sim.active=true;step(sim,5);assert.equal(sim.s.tiles[H.BASIN[0]],'water');});
test('migration v8 keeps started second arenas; finished garden progress remains unchanged',()=>{for(const status of ['dormant','active','cleared','restored']){const s=A.createState();s.version=8;delete s.archive;s.shrines[1].status=status;s.chapter= A.chapter.initial(true);s.shards=23;const before=JSON.stringify(s),next=A.migrateSave(s);assert.equal(next.version,9);assert.equal(next.archive.stage,status==='dormant'?'unmet':'legacy');assert.equal(next.shrines[1].status,status);assert.equal(next.shards,23);assert.deepEqual(next.chapter,s.chapter);assert.equal(JSON.stringify(s),before);assert.deepEqual(A.migrateSave(next),next);}});
test('damaged archive saves cannot inject records, skip evidence or poison device timers',()=>{for(const change of [q=>q.stage='bad',q=>q.records=['catalogue','catalogue'],q=>q.records=['bad'],q=>q.stage='restore',q=>q.surge=4,q=>q.surge=-1,q=>q.lift=Infinity,q=>q.lift=3.1,q=>q.prepared=null]){const s=A.createState();change(s.archive);assert.equal(A.migrateSave(s),null);}});
test('garden outcome changes Nera introduction without disclosing undiscovered mana',()=>{const sim=scene();sim.s.chapter.choice='grove';assert.match(H.dialogue(sim,'nera').text,/сохранили рощу/);sim.s.chapter.choice='spring';assert.match(H.dialogue(sim,'nera').text,/вернули воду/);assert.deepEqual(sim.s.knowledge.known,['earth','water','air']);});
