'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),A=require('../core.js'),Q=A.chapter,Simulation=require('../simulation.js');
function setup(){const s=A.createState();s.worldPopulated=s.magesPopulated=s.ecology.populated=true;s.tutorial=5;return new Simulation(s);}
function step(sim,seconds){for(let i=0;i<Math.ceil(seconds/.025);i++)sim.update(.025);}
function visit(sim,m){Object.assign(sim.s.player,{x:m.x,y:m.y});sim.interact();}
function investigate(sim){visit(sim,Q.IVA);assert.ok(Q.choose(sim,'accept'));for(const c of Q.CLUES)visit(sim,c);}
function rescue(sim){investigate(sim);visit(sim,Q.START);assert.ok(Q.choose(sim,'escort'));sim.s.player.x=1300;sim.s.player.y=2060;sim.s.player.mana.air=60;assert.ok(sim.cast({x:1380,y:2060},false,{element:'air',form:'burst',mod:'plain'}));step(sim,5);assert.equal(sim.s.chapter.stage,'choice');}
test('chapter sites remain reachable and preparation preserves player walls on 30 seeds',()=>{for(let seed=0;seed<30;seed++){const s=A.createState(seed);s.worldPopulated=s.magesPopulated=s.ecology.populated=true;const sim=new Simulation(s);for(const p of [Q.IVA,...Q.CLUES,Q.START,Q.END])assert.ok(A.reachable(s.tiles,53*104+52,Math.floor(p.y/40)*104+Math.floor(p.x/40)),`seed ${seed}: ${p.name||'rescue'}`);assert.ok(A.validSave(s));}const s=A.createState();s.tiles[50*104+34]='barrier';s.walls[50*104+34]={hp:80,maxHp:80,material:'earth'};new Simulation(s);assert.equal(s.tiles[50*104+34],'barrier');});
test('investigation requires both distinct clues and remote or out-of-order choices fail',()=>{const sim=setup();assert.equal(Q.choose(sim,'accept'),false);assert.equal(Q.choose(sim,'grove'),false);visit(sim,Q.IVA);assert.equal(sim.s.chapter.stage,'unmet');assert.ok(Q.choose(sim,'accept'));visit(sim,Q.CLUES[1]);assert.equal(sim.s.chapter.stage,'investigate');assert.equal(Q.interact(sim,Q.CLUES[1].id),false);visit(sim,Q.CLUES[0]);assert.equal(sim.s.chapter.stage,'rescue');assert.equal(sim.s.chapter.clues.length,2);assert.equal(Q.choose(sim,'escort'),false);assert.equal(sim.s.shards,0);});
test('first seal cannot bypass the story or spawn guards and take a premature mana payment',()=>{const sim=setup(),p=sim.s.player;p.mana.earth=p.mana.life=60;visit(sim,{x:1100,y:1940});assert.equal(sim.s.shrines[0].status,'dormant');assert.equal(p.mana.earth,60);assert.equal(sim.s.enemies.length,0);});
test('escort waits for agreement, player proximity and removal of real fire',()=>{const sim=setup();investigate(sim);step(sim,2);assert.equal(sim.s.chapter.lev.y,1980);visit(sim,Q.START);Q.choose(sim,'escort');Object.assign(sim.s.player,{x:1940,y:2140});step(sim,2);assert.equal(sim.s.chapter.lev.y,1980);Object.assign(sim.s.player,{x:1300,y:2060});step(sim,4);assert.ok(sim.s.chapter.lev.y<2000);assert.equal(sim.s.chapter.stage,'escort');assert.equal(sim.s.tiles[51*104+34],'fire');});
test('paid air magic clears the rescue route and escort reaches safety without any kills',()=>{const sim=setup();rescue(sim);assert.equal(sim.s.chapter.lev.y,2140);assert.equal(sim.s.stats.kills,0);assert.equal(sim.s.stats.casts,1);for(const y of [50,51,52])assert.notEqual(sim.s.tiles[y*104+34],'fire');});
test('paid water projectiles extinguish each route tile and permit rescue',()=>{const sim=setup();investigate(sim);visit(sim,Q.START);Q.choose(sim,'escort');sim.s.player.x=1300;sim.s.player.y=2060;sim.s.player.mana.water=60;for(const y of [2020,2060,2100]){sim.cooldown=0;assert.ok(sim.cast({x:1380,y},false,{element:'water',form:'bolt',mod:'plain'}));step(sim,.8);}step(sim,5);assert.equal(sim.s.chapter.stage,'choice');assert.equal(sim.s.stats.casts,3);});
test('both choices change distinct renewable sources, pay once, restore and grant one reward',()=>{for(const choice of ['grove','spring']){const sim=setup();rescue(sim);visit(sim,Q.IVA);assert.ok(Q.choose(sim,choice));assert.equal(Q.choose(sim,choice==='grove'?'spring':'grove'),false);sim.s.player.mana.earth=24;sim.s.player.mana.water=60;visit(sim,{x:1100,y:1940});assert.equal(sim.s.chapter.stage,'restore');assert.equal(sim.s.player.mana.water,60);sim.s.player.mana.earth=60;visit(sim,{x:1100,y:1940});assert.equal(sim.s.chapter.stage,'done');assert.equal(sim.s.shrines[0].status,'restored');assert.equal(sim.s.player.mana.earth,35);assert.equal(sim.s.player.mana.water,45);assert.equal(sim.s.shards,12);assert.equal(sim.s.enemies.length,0);assert.ok(sim.chooseRelic('roots'));assert.equal(sim.chooseRelic('roots'),false);for(const i of Q.PATCH)assert.equal(sim.s.tiles[i],choice==='grove'?'tree':'water');const rates=A.manaRates(sim.s.tiles,{x:1100,y:2060},false,[],80);assert.ok(rates[choice==='grove'?'life':'water']>0);visit(sim,{x:1100,y:1940});assert.equal(sim.s.shards,12);assert.equal(sim.s.player.mana.earth,35);assert.ok(A.validSave(sim.s));}});
test('saving every stage preserves progress, choices and extinguished terrain without reseeding',()=>{const sim=setup();for(const run of [()=>{},()=>{visit(sim,Q.IVA);Q.choose(sim,'accept');},()=>{for(const c of Q.CLUES)visit(sim,c);},()=>{visit(sim,Q.START);Q.choose(sim,'escort');},()=>{sim.transform(1380,2060,100,'air');Object.assign(sim.s.player,{x:1300,y:2060});step(sim,5);},()=>{visit(sim,Q.IVA);Q.choose(sim,'spring');},()=>{sim.s.player.mana.earth=sim.s.player.mana.water=60;visit(sim,{x:1100,y:1940});}]){run();const save=A.migrateSave(sim.s);assert.ok(save);const loaded=new Simulation(save);assert.deepEqual(loaded.s.chapter,sim.s.chapter);assert.deepEqual(loaded.s.tiles,sim.s.tiles);}});
test('death preserves escort and clues; it never teleports or refills the rescue fires',()=>{const sim=setup();investigate(sim);visit(sim,Q.START);Q.choose(sim,'escort');sim.transform(1380,2060,100,'air');Object.assign(sim.s.player,{x:1300,y:2060});step(sim,1);const y=sim.s.chapter.lev.y;sim.die();step(sim,1);assert.equal(sim.s.chapter.lev.y,y);assert.equal(sim.s.chapter.stage,'escort');assert.equal(sim.s.chapter.clues.length,2);assert.equal(sim.s.tiles[51*104+34],'soil');});
test('v7 migration preserves awakened/completed arenas and offers chapter for dormant seal',()=>{for(const status of ['dormant','active','cleared','restored']){const s=A.createState();s.version=7;delete s.chapter;s.shrines[0].status=status;s.shards=27;const before=JSON.stringify(s),loaded=A.migrateSave(s);assert.equal(loaded.version,8);assert.equal(loaded.chapter.stage,status==='dormant'?'unmet':'legacy');assert.equal(loaded.shards,27);assert.equal(loaded.shrines[0].status,status);assert.equal(JSON.stringify(s),before);}});
test('malformed quest state is rejected instead of trapping the player on reload',()=>{for(const change of [q=>q.stage='missing',q=>q.clues=['letter','letter'],q=>q.clues=['injected'],q=>q.lev.y=NaN,q=>q.lev.x=0,q=>q.choice='bad',q=>q.stage='done',q=>q.prepared=null]){const s=A.createState();change(s.chapter);assert.equal(A.migrateSave(s),null);}});
