const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../core.js'),Simulation=require('../simulation.js');
// Combat agent uses paid spells, normal movement, shield/healing and the real AI.
// Fixtures position a prepared player at a seal; they do not reduce enemy damage.
function fight(sim,maxSeconds=240){const s=sim.s,p=s.player,origin={x:p.x,y:p.y};let elapsed=0;while(elapsed<maxSeconds&&(s.boss||s.enemies.some(e=>e.guard>=0))){const enemies=s.boss?[...s.enemies,s.boss]:s.enemies;const target=enemies.filter(e=>e.hp>0).sort((a,b)=>A.dist(p,a)-A.dist(p,b))[0];if(!target)break;let vector={x:0,y:0};const d=A.dist(p,target),angle=Math.atan2(p.y-target.y,p.x-target.x);if(d<165)vector={x:Math.cos(angle),y:Math.sin(angle)};else if(d>265)vector={x:-Math.cos(angle),y:-Math.sin(angle)};else vector={x:Math.cos(angle+Math.PI/2)*.65,y:Math.sin(angle+Math.PI/2)*.65};if(A.dist(p,origin)>330)vector={x:origin.x-p.x,y:origin.y-p.y};
if(sim.cooldown<=0){if(p.hp<p.maxHp*.7&&p.mana.life>=10){s.spells[0]={form:'self',element:'life',mod:'plain'};sim.cast(p);}else if(p.shield<10&&p.mana.earth>=10){s.spells[0]={form:'self',element:'earth',mod:'plain'};sim.cast(p);}else{const element=['light','water','fire','shadow','air','earth','space','life'].filter(m=>p.mana[m]>=6).sort((a,b)=>p.mana[b]-p.mana[a])[0];if(element){s.spells[0]={form:'bolt',element,mod:'plain'};sim.cast(target);}}}
sim.update(.025,vector);elapsed+=.025;if(s.stats.deaths)break;}
return {elapsed:Math.round(elapsed),hp:Math.round(p.hp),dead:s.stats.deaths,left:s.enemies.filter(e=>e.guard>=0).length,boss:s.boss?.hp||0};}
test('a prepared player can beat the first seal using real paid casts and ordinary movement',()=>{const s=A.createState(31719),sim=new Simulation(s);s.enemies=[];const sh=s.shrines[0];s.player.x=(sh.x+.5)*40;s.player.y=(sh.y+.5)*40;for(const m of A.MANA)s.player.mana[m.id]=60;sim.interact();const result=fight(sim);assert.equal(result.dead,0,JSON.stringify(result));assert.equal(result.left,0,JSON.stringify(result));assert.equal(sh.status,'cleared');assert.ok(s.stats.casts>0);});
test('all seal encounters are beatable with a prepared late-game character',()=>{for(let seal=1;seal<5;seal++){const s=A.createState(31719),sim=new Simulation(s);s.enemies=[];for(let i=0;i<seal;i++)s.shrines[i].status='restored';s.relics=['roots','reservoir','heart','lens','stride'].slice(0,seal);s.player.maxHp=130;s.player.hp=130;s.player.cap=80;for(const m of A.MANA)s.player.mana[m.id]=80;const sh=s.shrines[seal];s.player.x=(sh.x+.5)*40;s.player.y=(sh.y+.5)*40;sim.interact();const result=fight(sim);assert.equal(result.dead,0,`seal ${seal}: ${JSON.stringify(result)}`);assert.equal(result.left,0,`seal ${seal}: ${JSON.stringify(result)}`);}});
test('finale can be beaten through real projectiles with all earned relics',()=>{const s=A.createState(31719),sim=new Simulation(s);s.enemies=[];s.relics=A.RELICS.map(r=>r.id);s.shrines.forEach(sh=>sh.status='restored');s.player.maxHp=s.player.hp=130;s.player.cap=80;for(const m of A.MANA)s.player.mana[m.id]=80;s.player.x=53.5*40;s.player.y=53.5*40;sim.startBoss();const result=fight(sim,300);assert.equal(result.dead,0,JSON.stringify(result));assert.equal(s.won,true,JSON.stringify(result));});
