const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../core.js'),Simulation=require('../simulation.js');
function emptySim(){const s=A.createState(123);const sim=new Simulation(s);s.enemies=[];return sim;}
function advance(sim,seconds,input={x:0,y:0}){for(let i=0;i<Math.ceil(seconds/.025);i++)sim.update(.025,input);}
test('world generation is reproducible and all five seals are reachable on 50 seeds',()=>{assert.deepEqual(A.makeWorld(55),A.makeWorld(55));for(let seed=0;seed<50;seed++){const t=A.makeWorld(seed);for(const shrine of A.SHRINES)assert.ok(A.reachable(t,53*A.SIZE+52,shrine.y*A.SIZE+shrine.x),`seed ${seed}: ${shrine.name}`);}});
test('all 240 spell combinations have finite positive costs and combine duplicate currencies',()=>{let count=0;for(const f of A.FORMS)for(const m of A.MANA)for(const mod of A.MODS){const c=A.cost({form:f.id,element:m.id,mod:mod.id});assert.ok(Object.values(c).every(v=>Number.isFinite(v)&&v>0));count++;}assert.equal(count,240);assert.equal(A.cost({form:'bolt',element:'space',mod:'echo'}).space,11);assert.equal(A.cost({form:'bolt',element:'air',mod:'reach'}).air,10);});
test('payment is atomic and never spends an insufficient pool',()=>{const mana={earth:10,water:2};assert.equal(A.pay(mana,{earth:3,water:3}),false);assert.deepEqual(mana,{earth:10,water:2});assert.equal(A.pay(mana,{earth:3,water:2}),true);assert.deepEqual(mana,{earth:7,water:0});});
test('mana has conditional sources, rather than passive universal regeneration',()=>{const tiles=Array(A.SIZE*A.SIZE).fill('stone'),p={x:500,y:500};let rates=A.manaRates(tiles,p,false,[],240);assert.equal(rates.earth,3.6);assert.ok(Object.entries(rates).filter(([id])=>id!=='earth').every(([,v])=>v===0));rates=A.manaRates(tiles,p,true,[],240);assert.equal(rates.earth,0);assert.equal(rates.air,2.7);const idx=12*A.SIZE+12;tiles[idx]='water';assert.equal(A.manaRates(tiles,p,false,[],240).water,3);tiles[idx]='rift';assert.equal(A.manaRates(tiles,p,false,[],240).space,2.8);assert.equal(A.manaRates(tiles,p,false,[],240).shadow,2.6);});
test('the environment supports all eight mana sources near initial sanctuary',()=>{const s=A.createState();const available=new Set();for(let dy=-6;dy<=6;dy++)for(let dx=-6;dx<=6;dx++){const rates=A.manaRates(s.tiles,{x:(52.5+dx)*40,y:(53.5+dy)*40},false);for(const [k,v]of Object.entries(rates))if(v>0)available.add(k);}available.add('air');assert.equal(available.size,8);});
test('terrain reactions create renewable sources and never modify the boundary',()=>{assert.equal(A.terrainReaction('lava','water'),'obsidian');assert.equal(A.terrainReaction('soil','life'),'tree');assert.equal(A.terrainReaction('tree','fire'),'fire');assert.equal(A.terrainReaction('crystal','shadow'),'rift');assert.equal(A.terrainReaction('rift','light'),'crystal');const sim=emptySim();sim.transform(0,0,200,'earth');assert.equal(sim.s.tiles[0],'wall');});
test('cast lands at the aimed ground position and can create a water source',()=>{const sim=emptySim(),p=sim.s.player;p.mana.water=30;sim.s.spells[0]={form:'bolt',element:'water',mod:'plain'};const target={x:p.x+80,y:p.y};const idx=Math.floor(target.y/40)*A.SIZE+Math.floor(target.x/40);sim.s.tiles[idx]='soil';assert.equal(sim.cast(target),true);advance(sim,.3);assert.equal(sim.s.tiles[idx],'water');assert.ok(p.mana.water<30);});
test('blocked casting never creates a free effect; echoes charge once',()=>{const sim=emptySim(),p=sim.s.player;p.mana.earth=0;assert.equal(sim.cast({x:p.x+100,y:p.y}),false);assert.equal(sim.projectiles.length,0);sim.cooldown=0;p.mana.earth=20;p.mana.space=20;sim.s.spells[0]={form:'bolt',element:'earth',mod:'echo'};sim.cast({x:p.x+300,y:p.y});assert.equal(p.mana.earth,14);assert.equal(p.mana.space,15);advance(sim,.4,{x:0,y:1});assert.equal(sim.s.stats.casts,1);assert.equal(sim.delayed.length,0);assert.ok(sim.projectiles.length>=1);});
test('healing, shield, dash and teleport are functional and obey collision bounds',()=>{const sim=emptySim(),p=sim.s.player;p.hp=20;sim.cast(p,true,{form:'self',element:'life',mod:'plain'});assert.equal(p.hp,50);sim.cast(p,true,{form:'self',element:'earth',mod:'plain'});assert.equal(p.shield,38);sim.hurt(15);assert.equal(p.shield,23);assert.equal(p.hp,50);const old=p.x;sim.dash(1,0);assert.ok(p.x>old);assert.ok(p.mana.air<24);sim.cast({x:-500,y:-500},true,{form:'self',element:'space',mod:'plain'});assert.ok(p.x>40&&p.y>40);assert.equal(sim.blocked(p.x,p.y),false);});
test('enemy projectiles damage player, shield absorbs and burn can kill enemies',()=>{const sim=emptySim(),p=sim.s.player;sim.projectiles.push({x:p.x,y:p.y,vx:0,vy:0,r:6,life:1,enemy:true,damage:10});advance(sim,.025);assert.equal(p.hp,90);const e=sim.spawn('crawler',p.x+100,p.y);e.hp=1;e.burn=1;advance(sim,.3);assert.equal(sim.s.stats.kills,1);assert.ok(sim.s.pickups.length>0||sim.s.shards>0);});
test('death keeps progression, charges shards once, and preserves active shrine encounter',()=>{const sim=emptySim(),p=sim.s.player;sim.s.shards=30;sim.s.shrines[0].status='active';const e=sim.spawn('crawler',p.x+100,p.y,0);e.hp=1;p.hp=1;sim.hurt(20);assert.equal(sim.s.stats.deaths,1);assert.equal(sim.s.shards,24);assert.equal(p.hp,p.maxHp);assert.equal(e.hp,e.maxHp);assert.equal(sim.s.shrines[0].status,'active');assert.ok(A.validSave(JSON.parse(JSON.stringify(sim.s))));});
test('complete campaign state transitions: pay, fight, restore, research, relics, finale',()=>{const sim=emptySim(),s=sim.s,p=s.player;for(let i=0;i<5;i++){const sh=s.shrines[i];p.x=(sh.x+.5)*40;p.y=(sh.y+.5)*40;p.mana[sh.element]=60;p.mana[sh.second]=60;sim.interact();assert.equal(sh.status,'active');assert.ok(s.enemies.some(e=>e.guard===i));for(const e of s.enemies.filter(e=>e.guard===i))sim.hit(e,1000,{element:'light',mod:'plain'},p.x,p.y);advance(sim,.025);assert.equal(sh.status,'cleared');sim.interact();assert.equal(sh.status,'restored');assert.equal(sim.chooseRelic(A.RELICS[i].id),true);assert.equal(sim.chooseRelic(A.RELICS[i].id),false);}
assert.equal(sim.level,5);assert.equal(p.cap,80);assert.equal(p.maxHp,130);s.shards=48;assert.equal(sim.research(),true);assert.equal(sim.research(),true);assert.equal(sim.research(),true);assert.equal(sim.research(),false);assert.equal(s.research,3);sim.startBoss();assert.equal(s.boss.kind,'boss');const boss=s.boss;sim.hit(boss,10000,{element:'water',mod:'plain'},p.x,p.y);assert.equal(s.won,true);assert.equal(s.boss,null);assert.ok(sim.events.some(e=>e.type==='victory'));assert.ok(A.validSave(JSON.parse(JSON.stringify(s))));});
test('save schema rejects corrupt tiles, invalid spells and negative mana',()=>{let s=A.createState();assert.equal(A.validSave(s),true);s.tiles[0]='bad';assert.equal(A.validSave(s),false);s=A.createState();s.spells[0].element='bad';assert.equal(A.validSave(s),false);s=A.createState();s.player.mana.earth=-1;assert.equal(A.validSave(s),false);});
test('sustained simulation remains finite and mana stays capped',()=>{const sim=new Simulation(A.createState(541));for(let i=0;i<12000;i++){sim.update(.025,{x:Math.cos(i/800),y:Math.sin(i/800)});if(i%40===0)sim.cast({x:sim.s.player.x+100,y:sim.s.player.y});}assert.ok(Number.isFinite(sim.s.player.x));for(const v of Object.values(sim.s.player.mana))assert.ok(v>=0&&v<=sim.s.player.cap);assert.ok(sim.s.enemies.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.hp)));});
