'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),A=require('../core.js'),E=require('../ecology.js'),Simulation=require('../simulation.js');
function setup(){const s=A.createState();s.worldPopulated=true;s.ecology.populated=true;s.tiles.fill('ruin');s.player.x=1620;s.player.y=1620;s.time=240;for(const id in s.player.mana)s.player.mana[id]=40;return new Simulation(s);}
function step(sim,seconds){for(let i=0;i<Math.round(seconds/.025);i++)sim.update(.025);}
function anomaly(sim,element='water'){const a={id:1,x:1720,y:1620,element,neutralized:false};sim.s.ecology.anomalies.push(a);return a;}
function leech(sim,element='water'){const e=sim.spawn('leech',1720,1620);e.speed=0;e.drainElement=element;return e;}
const spell=(element,form='bolt')=>({element,form,mod:'plain'});
test('leech warns before draining only its selected vessel without damage or healing',()=>{const sim=setup(),e=leech(sim),p=sim.s.player,before={...p.mana};e.hp=20;step(sim,.75);assert.equal(p.mana.water,40);assert.equal(sim.drainLinks[0].active,false);step(sim,.6);assert.ok(p.mana.water<38);for(const key of Object.keys(before).filter(x=>x!=='water'))assert.equal(p.mana[key],before[key]);assert.equal(p.hp,100);assert.equal(e.hp,20);assert.ok(sim.s.knowledge.facts.includes('ecology:drain:water'));});
test('empty vessels stop the channel without switching mana or manufacturing event rewards',()=>{const sim=setup();leech(sim);sim.s.player.mana.water=.1;step(sim,2);assert.equal(sim.s.player.mana.water,0);assert.equal(sim.s.player.mana.life,40);assert.equal(sim.drainLinks.length,0);assert.equal(sim.s.player.mana.blood,40);assert.equal(sim.s.player.mana.death,40);sim.s.player.mana.water=10;step(sim,.5);assert.equal(sim.s.player.mana.water,10);});
test('leaving range and stone cover reset the warning period',()=>{const sim=setup();anomaly(sim);step(sim,1.5);const p=sim.s.player,remaining=p.mana.water;p.x=1420;step(sim,.2);assert.equal(p.mana.water,remaining);p.x=1620;step(sim,.7);assert.equal(p.mana.water,remaining);sim.s.tiles[40*104+41]='wall';step(sim,2);assert.equal(p.mana.water,remaining);assert.equal(sim.drainLinks.length,0);sim.s.tiles[40*104+41]='ruin';step(sim,.7);assert.equal(p.mana.water,remaining);});
test('paid earth-air wall interrupts a live leech link',()=>{const sim=setup(),e=leech(sim);e.x=e.homeX=1780;sim.s.tiles.fill('soil');step(sim,1.2);assert.ok(sim.drains.water>0);assert.ok(sim.cast({x:1700,y:1620},false,{elements:['earth','air'],form:'bolt',mod:'plain'}));step(sim,.25);assert.ok(Object.keys(sim.s.walls).length);assert.equal(sim.drains.water||0,0);});
test('free spark interrupts a leech and it must recover then warn again',()=>{const sim=setup(),e=leech(sim);step(sim,1);sim.hit(e,1,spell('air'),1620,1620);const mana=sim.s.player.mana.water;step(sim,1.2);assert.equal(sim.s.player.mana.water,mana);assert.ok(sim.s.knowledge.facts.includes('ecology:interrupt'));});
test('fear and stun suppress leech channels and death removes the source',()=>{for(const status of ['fear','stun']){const sim=setup(),e=leech(sim);e[status]=3;e.fearX=1620;e.fearY=1620;step(sim,1);assert.equal(sim.s.player.mana.water,40);e.hp=0;step(sim,.1);assert.equal(sim.drainLinks.length,0);assert.equal(sim.channels.size,0);}});
test('each anomaly responds to its counter as a real paid projectile and rewards once',()=>{for(const [element,type]of Object.entries(E.TYPES)){const sim=setup(),a=anomaly(sim,element);assert.ok(sim.cast(a,false,spell(type.counter)));step(sim,.4);assert.equal(a.neutralized,true,element);assert.equal(sim.s.shards,3);assert.ok(sim.s.knowledge.facts.includes('ecology:counter:'+element));sim.cooldown=0;sim.cast(a,false,spell(type.counter));step(sim,.4);assert.equal(sim.s.shards,3);assert.equal(sim.s.stats.kills,0);}});
test('wrong magic does not neutralize or reveal the correct counter',()=>{const sim=setup(),a=anomaly(sim,'fire');sim.cast(a,false,spell('earth'));step(sim,.4);assert.equal(a.neutralized,false);assert.equal(sim.s.shards,0);assert.equal(sim.s.knowledge.facts.some(x=>x.startsWith('ecology:counter:')),false);});
test('free air spark can neutralize the first earth anomaly without mana',()=>{const sim=setup(),a=anomaly(sim,'earth');for(const id in sim.s.player.mana)sim.s.player.mana[id]=0;sim.projectiles.push({x:sim.s.player.x,y:sim.s.player.y,vx:390,vy:0,life:.75,r:4,spell:spell('air'),power:1/3,color:'#fff',enemy:false});step(sim,.4);assert.equal(a.neutralized,true);assert.equal(sim.s.shards,3);});
test('multiple sources clamp extraction to available mana',()=>{const sim=setup();anomaly(sim);leech(sim);sim.s.player.mana.water=3;step(sim,3);assert.equal(sim.s.player.mana.water,0);assert.equal(sim.s.player.hp,100);assert.ok(A.validSave(sim.s));});
test('pause freezes channels and loading retains neutralization but restarts warning',()=>{const sim=setup(),a=anomaly(sim);step(sim,.8);sim.active=false;step(sim,2);assert.equal(sim.s.player.mana.water,40);sim.active=true;step(sim,.6);assert.ok(sim.s.player.mana.water<40);const loaded=new Simulation(A.migrateSave(sim.s)),before=loaded.s.player.mana.water;step(loaded,.8);assert.equal(loaded.s.player.mana.water,before);a.neutralized=true;const restored=new Simulation(A.migrateSave(sim.s));assert.equal(restored.s.ecology.anomalies[0].neutralized,true);step(restored,2);assert.equal(restored.drainLinks.length,0);});
test('v5 migration retains walls and progression and ecology populates just once',()=>{const sim=setup();sim.s.version=5;delete sim.s.ecology;sim.s.shards=23;const migrated=A.migrateSave(sim.s);assert.equal(migrated.version,6);assert.equal(migrated.shards,23);const next=new Simulation(migrated),count=next.s.enemies.length,sites=JSON.stringify(next.s.ecology);assert.ok(count>0);new Simulation(next.s);assert.equal(next.s.enemies.length,count);assert.equal(JSON.stringify(next.s.ecology),sites);});
test('invalid ecology saves and unsupported leech vessels are rejected',()=>{for(const mutate of [s=>delete s.ecology,s=>s.ecology.anomalies=[{id:1,x:1,y:1,element:'water',neutralized:false}],s=>{const a={id:1,x:100,y:100,element:'water',neutralized:false};s.ecology.anomalies=[a,a];},s=>{s.enemies[0].drainElement='blood';}]){const sim=setup();leech(sim);mutate(sim.s);assert.equal(A.validSave(sim.s),false);}});
test('new habitats stay outside sanctuary and generate deterministically on twelve worlds',()=>{for(let seed=1;seed<=12;seed++){const a=new Simulation(A.createState(seed)),b=new Simulation(A.createState(seed));assert.deepEqual(a.s.ecology,b.s.ecology);assert.equal(a.s.ecology.anomalies.length,4);assert.equal(a.s.enemies.filter(e=>e.kind==='leech').length,8);for(const site of a.s.ecology.anomalies){assert.ok(A.dist(site,a.s.checkpoint)>360);assert.equal(a.blocked(site.x,site.y,18),false);}for(const e of a.s.enemies.filter(e=>e.kind==='leech'))assert.ok(!['lava','fire'].includes(a.tile(e.x,e.y)));assert.ok(A.validSave(a.s));}});
