const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../core.js'),K=require('../knowledge.js'),Simulation=require('../simulation.js');
function setup(){const s=A.createState(42),sim=new Simulation(s);s.enemies=[];s.tiles.fill('soil');return sim;}
function step(sim,n=1){for(let i=0;i<n;i++)sim.update(.025);}
function foe(sim,kind='crawler',guard=-1){const p=sim.s.player;return sim.spawn(kind,p.x+80,p.y,guard);}
function strike(sim,e,damage,element='air'){sim.hit(e,damage,{element,form:'bolt',mod:'plain'},e.x-1,e.y);}
function reload(sim){const s=A.migrateSave(JSON.parse(JSON.stringify(sim.s)));assert.ok(s);return new Simulation(s);}
test('new journey teaches three basics and starts event vessels empty',()=>{const s=A.createState();assert.deepEqual(s.knowledge.known,['earth','water','air']);assert.equal(s.player.mana.blood,0);assert.equal(s.player.mana.death,0);assert.ok(s.spells.every(p=>K.BASIC.includes(p.element)));const sim=setup();step(sim,200);sim.die();assert.equal(sim.s.player.mana.blood,0);assert.equal(sim.s.player.mana.death,0);});
test('blood measures real living health loss after resistance and overkill',()=>{const sim=setup(),p=sim.s.player,e=foe(sim);strike(sim,e,20,'life');assert.equal(p.mana.blood,.2);e.hp=2;strike(sim,e,1000);assert.ok(Math.abs(p.mana.blood-.6)<1e-9);assert.equal(p.mana.death,4);assert.ok(sim.s.knowledge.facts.includes('source:blood:dealt'));for(const kind of ['brute','sentinel','shade','wisp'])strike(sim,foe(sim,kind),2,'light');assert.ok(Math.abs(p.mana.blood-.6)<1e-9);});
test('incoming blood excludes invulnerability, shields, hazards, friendly and summoned targets',()=>{const sim=setup(),p=sim.s.player,e=foe(sim);p.shield=12;sim.hurt(20,e);assert.equal(p.hp,92);assert.equal(p.mana.blood,2);sim.hurt(20,e);assert.equal(p.mana.blood,2);sim.invincible=0;sim.hurt(4);assert.equal(p.mana.blood,2);sim.invincible=0;sim.hurt(4,{...e,friendly:true});assert.equal(p.mana.blood,2);strike(sim,foe(sim,'crawler',99),100);assert.equal(p.mana.blood,2);const friend=foe(sim);friend.friendly=true;strike(sim,friend,100);assert.equal(p.mana.blood,2);assert.equal(p.mana.death,0);});
test('blood budgets survive death and save/load, and dying grants no new vessels',()=>{let sim=setup(),e=foe(sim),p=sim.s.player;strike(sim,e,40);sim.hurt(20,e);assert.equal(p.mana.blood,13);sim.die();sim=reload(sim);e=sim.s.enemies.find(x=>x.id===e.id);p=sim.s.player;assert.equal(p.mana.death,0);strike(sim,e,40);assert.equal(p.mana.blood,15.4);sim.invincible=0;sim.hurt(80,e);assert.equal(p.mana.blood,23.4);sim.die();sim.invincible=0;sim.hurt(20,e);assert.equal(p.mana.blood,23.4);});
test('death is awarded once, requires player participation nearby and excludes summons',()=>{const sim=setup(),p=sim.s.player,e=foe(sim);strike(sim,e,100);assert.equal(p.mana.death,4);sim.kill(e);assert.equal(p.mana.death,4);const natural=foe(sim);sim.damageEnemy(natural,100,'fire',undefined,'environment');assert.equal(p.mana.death,4);const far=foe(sim);far.x+=900;strike(sim,far,100);assert.equal(p.mana.death,4);const summoned=foe(sim,'shade',99);strike(sim,summoned,500,'light');assert.equal(p.mana.death,4);});
test('created fire credits damage and death, including after reload',()=>{let sim=setup();const e=foe(sim),idx=Math.floor(e.y/40)*104+Math.floor(e.x/40);sim.s.tiles[idx]='tree';sim.transform(e.x,e.y,20,'fire');sim=reload(sim);const restored=sim.s.enemies.find(x=>x.id===e.id);restored.hp=.1;step(sim);assert.ok(sim.s.player.mana.blood>0);assert.equal(sim.s.player.mana.death,4);});
test('empty populated worlds stay empty on reload and spawn IDs never reuse ledger entries',()=>{let sim=setup();const e=foe(sim);strike(sim,e,100);step(sim);const oldId=e.id;sim=reload(sim);assert.equal(sim.s.enemies.length,0);const next=foe(sim);assert.ok(next.id>oldId);strike(sim,next,100);assert.equal(sim.s.player.mana.death,8);});
test('retrying the boss cannot reset its blood reward budget',()=>{let sim=setup();sim.startBoss();const boss=sim.s.boss;sim.hurt(100,boss);const blood=sim.s.player.mana.blood;assert.equal(blood,25);sim=reload(sim);sim.startBoss();assert.equal(sim.s.eventLedger.boss.incoming,100);});
test('event vessels cap without overflow and siphon cannot become a substitute source',()=>{const sim=setup(),p=sim.s.player;p.mana.blood=59;p.mana.death=59;strike(sim,foe(sim),100);assert.equal(p.mana.blood,60);assert.equal(p.mana.death,60);p.mana.death=0;sim.hit(foe(sim,'shade',99),1000,{element:'death',mod:'siphon'},p.x,p.y);assert.equal(p.mana.death,0);});
test('paid blood and death spells have distinct effects and cannot heal from immune creatures',()=>{const sim=setup(),p=sim.s.player;p.mana.blood=20;p.hp=50;sim.cast(p,false,{element:'blood',form:'self',mod:'plain'});assert.equal(p.hp,74);assert.equal(p.mana.blood,10);assert.ok(sim.s.knowledge.facts.includes('self:blood'));strike(sim,foe(sim,'brute'),20,'blood');assert.equal(p.hp,74);strike(sim,foe(sim),10,'blood');assert.equal(p.hp,75.65);const e=foe(sim);strike(sim,e,10,'death');assert.equal(e.slow,2.5);p.mana.death=20;sim.cooldown=0;sim.cast(p,false,{element:'death',form:'self',mod:'plain'});assert.equal(p.mana.death,10);assert.equal(p.shield,24);});
test('observations are specific, persistent and not recorded for absent effects',()=>{let sim=setup(),p=sim.s.player;const fire=A.MANA.find(m=>m.id==='fire');assert.equal(K.view(sim.s.knowledge,fire).known,false);assert.equal(K.entries(sim.s.knowledge,'fire','effect').length,0);sim.cast(p,true,{element:'life',form:'self',mod:'plain'});assert.ok(!sim.s.knowledge.facts.includes('self:life'));sim.s.tiles[Math.floor(p.y/40)*104+Math.floor(p.x/40)]='lava';step(sim);assert.ok(sim.s.knowledge.facts.includes('source:fire:lava'));assert.ok(!sim.s.knowledge.facts.includes('source:fire:fire'));assert.equal(K.entries(sim.s.knowledge,'fire','effect').length,0);sim.transform(p.x,p.y,20,'water');assert.ok(sim.s.knowledge.facts.includes('terrain:water:lava:obsidian'));const count=sim.s.knowledge.facts.length;sim.transform(p.x,p.y,20,'water');assert.equal(sim.s.knowledge.facts.length,count);sim=reload(sim);assert.ok(sim.s.knowledge.facts.includes('terrain:water:lava:obsidian'));});
test('v1 migration preserves campaign, inventories and recipes without manufacturing old observations',()=>{const sim=setup(),s=sim.s;const enemy=foe(sim);enemy.hp=enemy.maxHp-10;s.spells[2]={element:'life',form:'self',mod:'plain'};s.player.mana.fire=32;s.research=2;s.shards=19;s.shrines[0].status='restored';const legacy=JSON.parse(JSON.stringify(s));legacy.version=1;for(const key of ['knowledge','worldPopulated','eventLedger','nextEnemyId','terrainCredit'])delete legacy[key];delete legacy.player.mana.blood;delete legacy.player.mana.death;const migrated=A.migrateSave(legacy);assert.ok(migrated);assert.equal(legacy.version,1);assert.equal(migrated.version,4);assert.deepEqual(migrated.spells,legacy.spells.map(A.normalizeSpell));assert.equal(migrated.player.mana.fire,32);assert.equal(migrated.player.mana.blood,0);assert.equal(migrated.shards,19);assert.equal(migrated.research,2);assert.equal(migrated.shrines[0].status,'restored');assert.ok(migrated.knowledge.known.includes('life'));assert.ok(!migrated.knowledge.facts.includes('self:life'));assert.equal(migrated.eventLedger['enemy:'+enemy.id].out,10);assert.deepEqual(A.migrateSave(migrated),migrated);});
test('corrupt knowledge, event records and future save versions are rejected',()=>{for(const mutate of [s=>s.version=99,s=>s.player.mana.death=-1,s=>s.knowledge.facts.push('injected'),s=>s.knowledge.known.push('invalid'),s=>s.eventLedger.boss={out:-1,incoming:0,dead:false},s=>s.terrainCredit[999999]=true,s=>s.nextEnemyId=NaN,s=>s.spells[0]=null,s=>s.enemies.push(null),s=>s.shrines[0]=null]){const s=A.createState();mutate(s);assert.equal(A.migrateSave(s),null);}});
