'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),A=require('../core.js'),G=require('../mages.js'),Simulation=require('../simulation.js');
function setup(school='earth'){const s=A.createState();s.worldPopulated=true;s.magesPopulated=true;s.ecology.populated=true;s.tiles.fill('ruin');s.player.x=1620;s.player.y=1620;s.time=240;s.player.mana.air=60;const sim=new Simulation(s),e=sim.spawn('mage',1820,1620);Object.assign(e,G.initial(school));e.speed=0;sim.mageBrain(e).recovery=0;return {sim,s,e};}
function step(sim,time,input){for(let i=0;i<Math.round(time/.025);i++)sim.update(.025,input);}
const spell=(elements,form='bolt')=>({elements,form,mod:'plain'});
test('mage pays the exact compiled multi-vessel price and uses player projectile speed',()=>{const {sim,s,e}=setup('frost'),recipe=G.SCHOOLS.frost.attack,before={...e.mana};assert.ok(sim.castFrom(e,s.player,recipe));assert.equal(e.mana.water,before.water-6);assert.equal(e.mana.air,before.air-6);assert.equal(Math.hypot(sim.projectiles[0].vx,sim.projectiles[0].vy),440);assert.deepEqual(sim.projectiles[0].spell,A.normalizeSpell(recipe));assert.equal(sim.castFrom(e,s.player,recipe),false);});
test('missing mana rejects the whole enemy cast without partial payment or free shots',()=>{const {sim,s,e}=setup('frost');e.mana.air=0;const before={...e.mana};assert.equal(sim.castFrom(e,s.player,G.SCHOOLS.frost.attack),false);assert.deepEqual(e.mana,before);assert.equal(sim.projectiles.length,0);});
test('enemy and player resolve frost through the same weighted impact and statuses',()=>{const a=setup('frost');a.sim.castFrom(a.e,a.s.player,G.SCHOOLS.frost.attack);step(a.sim,.5);const b=setup('frost');b.sim.hit(b.e,24,G.SCHOOLS.frost.attack,b.s.player.x,b.s.player.y);assert.ok(Math.abs((100-a.s.player.hp)-(85-b.e.hp))<1e-8);assert.ok(a.s.player.slow>0);assert.ok(b.e.slow>0);assert.ok(a.s.player.stun>0);});
test('preparation locks target, can be dodged, and does not spend before release',()=>{const {sim,s,e}=setup();step(sim,.4);assert.equal(e.mana.earth,18);assert.ok(sim.mageBrain(e).cast);s.player.y+=160;step(sim,1.1);assert.equal(s.player.hp,100);assert.equal(e.mana.earth,12);});
test('hits and fear interrupt preparation without paying or launching',()=>{for(const control of ['hit','fear']){const {sim,s,e}=setup();step(sim,.2);if(control==='hit')sim.hit(e,1,spell(['air']),s.player.x,s.player.y);else e.fear=2;step(sim,.5);assert.equal(sim.mageBrain(e).cast,null);assert.equal(e.mana.earth,18);assert.equal(sim.projectiles.filter(p=>p.enemy).length,0);}});
test('earth self spell creates the same shield on its caster only and shield absorbs damage',()=>{const {sim,s,e}=setup();assert.ok(sim.castFrom(e,e,G.SHIELD));assert.equal(e.shield,38);assert.equal(s.player.shield,0);const hp=e.hp;sim.damageEnemy(e,24,'earth');assert.equal(e.hp,hp);assert.equal(e.shield,14);sim.damageEnemy(e,100,'earth');assert.equal(e.hp,0);});
test('enemy burst damages player instead of allied enemies',()=>{const {sim,s,e}=setup();e.x=1700;const ally=sim.spawn('crawler',1730,1620);sim.castFrom(e,s.player,G.SCHOOLS.earth.close);assert.equal(s.player.hp,73);assert.equal(ally.hp,ally.maxHp);});
test('native and constructed walls stop mage projectiles',()=>{for(const material of ['wall','barrier']){const {sim,s,e}=setup('ember');s.tiles[40*104+43]=material;if(material==='barrier')s.walls[40*104+43]={hp:80,maxHp:80,material:'earth'};sim.castFrom(e,s.player,G.SCHOOLS.ember.attack);step(sim,.6);assert.equal(s.player.hp,100);if(material==='barrier')assert.equal(s.walls[40*104+43].material,'brick');}});
test('enemy-created fire is not credited to player and transformation counters stay unchanged',()=>{const {sim,s,e}=setup('ember');s.tiles[40*104+40]='tree';const count=s.stats.transforms;sim.castFrom(e,s.player,G.SCHOOLS.ember.attack);step(sim,.5);assert.equal(s.tiles[40*104+40],'fire');assert.equal(s.terrainCredit[40*104+40],undefined);assert.equal(s.stats.transforms,count);});
test('mage gathering uses real sources and capacity without generic regeneration',()=>{const {sim,s,e}=setup('ember');s.player.x=2400;for(const id in e.mana)e.mana[id]=0;step(sim,1);assert.equal(e.mana.fire,0);s.tiles[40*104+46]='fire';step(sim,1);assert.ok(Math.abs(e.mana.fire-3.4)<.001);e.mana.fire=59.9;step(sim,1);assert.equal(e.mana.fire,60);});
test('empty fire mage walks to a reachable source then loses access when player extinguishes it',()=>{const {sim,s,e}=setup('ember');e.speed=64;e.mana.fire=0;s.tiles[40*104+49]='fire';step(sim,2.5);assert.ok(e.x>1840);assert.ok(e.mana.fire>0);sim.transform(1980,1620,25,'water');const fire=e.mana.fire;step(sim,1.5);assert.equal(e.mana.fire,fire);assert.equal(sim.mageBrain(e).state,'Источник недоступен');});
test('unreachable source is not chosen through a closed wall',()=>{const {sim,s,e}=setup('ember');e.mana.fire=0;for(let y=1;y<103;y++)s.tiles[y*104+46]='wall';s.tiles[40*104+48]='fire';assert.equal(sim.magePath(e,G.SCHOOLS.ember.attack),null);});
test('mana, shields and specialization persist, preparation restarts on load, old saves migrate',()=>{const {sim,s,e}=setup('frost');e.mana.water=7;e.shield=13;step(sim,.2);const restored=new Simulation(A.migrateSave(s)),mage=restored.s.enemies[0];assert.equal(mage.mana.water,7);assert.equal(mage.shield,13);assert.equal(mage.school,'frost');assert.equal(restored.mageBrain(mage).cast,null);const old=A.createState();old.version=6;delete old.magesPopulated;assert.equal(A.migrateSave(old).version,7);});
test('invalid mage currencies, capacity and schools are rejected',()=>{for(const mutate of [e=>e.mana.fire=-1,e=>e.mana.air=61,e=>e.school='unknown',e=>e.cap=100,e=>e.shield=NaN]){const {s,e}=setup();mutate(e);assert.equal(A.validSave(s),false);}});
test('new worlds contain three safe mage roles once and completed worlds add none',()=>{for(let seed=1;seed<=8;seed++){const s=A.createState(seed),sim=new Simulation(s),mages=s.enemies.filter(e=>e.kind==='mage');assert.equal(mages.length,3);assert.deepEqual(mages.map(e=>e.school),['earth','frost','ember']);for(const e of mages){assert.ok(A.dist(e,s.player)>=350);assert.equal(sim.blocked(e.x,e.y,18),false);assert.ok(!['lava','fire'].includes(sim.tile(e.x,e.y)));}new Simulation(s);assert.equal(s.enemies.filter(e=>e.kind==='mage').length,3);}const s=A.createState();s.won=true;new Simulation(s);assert.equal(s.enemies.length,0);});

test('leeches and anomalies drain enemy vessels under the same range and warning rules',()=>{const {sim,s,e}=setup('frost');s.player.x=2400;e.mana.water=10;const leech=sim.spawn('leech',e.x+100,e.y);leech.speed=0;s.ecology.anomalies.push({id:1,x:e.x,y:e.y+70,element:'water',neutralized:false});step(sim,1.5);assert.ok(e.mana.water<5);assert.equal(s.player.mana.water,24);assert.ok(sim.drainLinks.some(l=>l.targetId===e.id));});
test('death and reload do not refill enemy mana or duplicate mage population',()=>{const {sim,s,e}=setup('ember');e.mana.fire=1;sim.die();assert.equal(e.mana.fire,1);const next=new Simulation(A.migrateSave(s));assert.equal(next.s.enemies.filter(e=>e.kind==='mage').length,1);assert.equal(next.s.enemies[0].mana.fire,1);});
